app = "propulse-serveur-final" # Remplacez par le nom que vous choisirez lors du 'fly launch'
primary_region = "cdg"

[build]
  builder = "paketobuildpacks/builder:base"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source="propulse_data"
  destination="/data"