# fly.toml app configuration file generated for propulse-serveur-final on 2025-08-23T19:34:37+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'propulse-serveur-final'
primary_region = 'cdg'

[build]
  builder = 'paketobuildpacks/builder:base'

[[mounts]]
  source = 'propulse_data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
